### ISSUE TITLE
Support for `cl100k_base` encoding, used by new OpenAI models?

### ISSUE THREAD

**Issue by ztangent** [chengchingwen/BytePairEncoding.jl#6]
Hi, thanks for writing this package! It's been super useful for the [GenGPT3.jl](https://github.com/probcomp/GenGPT3.jl/) package I've been developing for research.

OpenAI recently released newer completion models (`gpt-3.5-instruct-turbo`, `babbage-002` and `davinci-002`) that no longer use the old GPT-2 tokenizer, but instead use the new `cl100k_base` encoding. I was wondering if you plan to support this encoding at some point -- or if not, if you have any pointers on how I could implement it? Thanks!

**Comment by ztangent** [comment]
It looks like I would have to implement a function similar to `gpt2_tokenizer` that makes use of the following pattern string:

```
r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+",
```
(source: https://github.com/aiqinxuancai/TiktokenSharp/blob/3640d180bc42a827d2487e3d41fc03433e8b6647/TiktokenSharp/Services/EncodingManager.cs#L318-L325)

But on top of that, it seems like I would also have to implement a `gpt2_codemap` function? And I'm not sure what that does.

**Comment by chengchingwen** [comment]
> But on top of that, it seems like I would also have to implement a gpt2_codemap function? And I'm not sure what that does.

It's part of the implementation detail of the "byte-level" bpe. GPT2 use the same bpe implementation of a normal bpe, except the input string is transformed with the `codemap`. The `codemap` map the input codepoints to a different set of printable codepoints, so it can handle unseen unicode characters. Most (all?) of the "byte-level" bpe are using the same `codemap` (the one returned by `gpt2_codemap`). However, tiktoken seems to change this implementation. I guess they probably implement a bpe directly on byte array.

**Comment by ztangent** [comment]
Thanks for the explanation!

I found [code online](https://gist.github.com/xenova/a452a6474428de0182b17605a98631ee) where people had converted the tiktoken tokenizer format in to the HuggingFace format, and it seems like after the conversion, `cl100k_base` uses the same codemap --  the converted vocabulary file contains the special `Ġ` tokens that start-of-word spaces get converted to: https://huggingface.co/Xenova/gpt-4/raw/main/vocab.json


I'll probably download those vocabulary files and see whether I can get the tokenizer working with `cl100k_base` instead of the `gpt2` tokenization -- will let you know if it works!

**Comment by chengchingwen** [comment]
```julia
Dict((((token, rank) = split(line); base64decode(token) => parse(Int, rank)) for line in readlines("cl100k_base.tiktoken")))
```

You can use this function to load the tiktoken `mergeable_ranks` and run the convert code (`bpe`) they provided.

**Comment by chengchingwen** [comment]
It seems we can actually directly implement the way tiktoken used. I open the pr at #7

**Comment by ztangent** [comment]
Awesome, thank you for supporting this so quickly!
